# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pianka/BadgerEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pianka/BadgerEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pianka/BadgerEngine/CMakeFiles /home/pianka/BadgerEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pianka/BadgerEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named badger

# Build rule for target.
badger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 badger
.PHONY : badger

# fast build rule for target.
badger/fast:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/build
.PHONY : badger/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f badger/vendor/GLFW/CMakeFiles/uninstall.dir/build.make badger/vendor/GLFW/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f badger/vendor/GLFW/src/CMakeFiles/glfw.dir/build.make badger/vendor/GLFW/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f badger/vendor/GLAD/CMakeFiles/glad.dir/build.make badger/vendor/GLAD/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f badger/vendor/imgui/CMakeFiles/imgui.dir/build.make badger/vendor/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

badger/src/Badger/Application.o: badger/src/Badger/Application.cpp.o

.PHONY : badger/src/Badger/Application.o

# target to build an object file
badger/src/Badger/Application.cpp.o:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Application.cpp.o
.PHONY : badger/src/Badger/Application.cpp.o

badger/src/Badger/Application.i: badger/src/Badger/Application.cpp.i

.PHONY : badger/src/Badger/Application.i

# target to preprocess a source file
badger/src/Badger/Application.cpp.i:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Application.cpp.i
.PHONY : badger/src/Badger/Application.cpp.i

badger/src/Badger/Application.s: badger/src/Badger/Application.cpp.s

.PHONY : badger/src/Badger/Application.s

# target to generate assembly for a file
badger/src/Badger/Application.cpp.s:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Application.cpp.s
.PHONY : badger/src/Badger/Application.cpp.s

badger/src/Badger/ImGui/ImGuiLayer.o: badger/src/Badger/ImGui/ImGuiLayer.cpp.o

.PHONY : badger/src/Badger/ImGui/ImGuiLayer.o

# target to build an object file
badger/src/Badger/ImGui/ImGuiLayer.cpp.o:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/ImGui/ImGuiLayer.cpp.o
.PHONY : badger/src/Badger/ImGui/ImGuiLayer.cpp.o

badger/src/Badger/ImGui/ImGuiLayer.i: badger/src/Badger/ImGui/ImGuiLayer.cpp.i

.PHONY : badger/src/Badger/ImGui/ImGuiLayer.i

# target to preprocess a source file
badger/src/Badger/ImGui/ImGuiLayer.cpp.i:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/ImGui/ImGuiLayer.cpp.i
.PHONY : badger/src/Badger/ImGui/ImGuiLayer.cpp.i

badger/src/Badger/ImGui/ImGuiLayer.s: badger/src/Badger/ImGui/ImGuiLayer.cpp.s

.PHONY : badger/src/Badger/ImGui/ImGuiLayer.s

# target to generate assembly for a file
badger/src/Badger/ImGui/ImGuiLayer.cpp.s:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/ImGui/ImGuiLayer.cpp.s
.PHONY : badger/src/Badger/ImGui/ImGuiLayer.cpp.s

badger/src/Badger/Layer.o: badger/src/Badger/Layer.cpp.o

.PHONY : badger/src/Badger/Layer.o

# target to build an object file
badger/src/Badger/Layer.cpp.o:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Layer.cpp.o
.PHONY : badger/src/Badger/Layer.cpp.o

badger/src/Badger/Layer.i: badger/src/Badger/Layer.cpp.i

.PHONY : badger/src/Badger/Layer.i

# target to preprocess a source file
badger/src/Badger/Layer.cpp.i:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Layer.cpp.i
.PHONY : badger/src/Badger/Layer.cpp.i

badger/src/Badger/Layer.s: badger/src/Badger/Layer.cpp.s

.PHONY : badger/src/Badger/Layer.s

# target to generate assembly for a file
badger/src/Badger/Layer.cpp.s:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Layer.cpp.s
.PHONY : badger/src/Badger/Layer.cpp.s

badger/src/Badger/LayerStack.o: badger/src/Badger/LayerStack.cpp.o

.PHONY : badger/src/Badger/LayerStack.o

# target to build an object file
badger/src/Badger/LayerStack.cpp.o:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/LayerStack.cpp.o
.PHONY : badger/src/Badger/LayerStack.cpp.o

badger/src/Badger/LayerStack.i: badger/src/Badger/LayerStack.cpp.i

.PHONY : badger/src/Badger/LayerStack.i

# target to preprocess a source file
badger/src/Badger/LayerStack.cpp.i:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/LayerStack.cpp.i
.PHONY : badger/src/Badger/LayerStack.cpp.i

badger/src/Badger/LayerStack.s: badger/src/Badger/LayerStack.cpp.s

.PHONY : badger/src/Badger/LayerStack.s

# target to generate assembly for a file
badger/src/Badger/LayerStack.cpp.s:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/LayerStack.cpp.s
.PHONY : badger/src/Badger/LayerStack.cpp.s

badger/src/Badger/Log.o: badger/src/Badger/Log.cpp.o

.PHONY : badger/src/Badger/Log.o

# target to build an object file
badger/src/Badger/Log.cpp.o:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Log.cpp.o
.PHONY : badger/src/Badger/Log.cpp.o

badger/src/Badger/Log.i: badger/src/Badger/Log.cpp.i

.PHONY : badger/src/Badger/Log.i

# target to preprocess a source file
badger/src/Badger/Log.cpp.i:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Log.cpp.i
.PHONY : badger/src/Badger/Log.cpp.i

badger/src/Badger/Log.s: badger/src/Badger/Log.cpp.s

.PHONY : badger/src/Badger/Log.s

# target to generate assembly for a file
badger/src/Badger/Log.cpp.s:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Log.cpp.s
.PHONY : badger/src/Badger/Log.cpp.s

badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.o: badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.o

.PHONY : badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.o

# target to build an object file
badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.o
.PHONY : badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.o

badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.i: badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.i

.PHONY : badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.i

# target to preprocess a source file
badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.i
.PHONY : badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.i

badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.s: badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.s

.PHONY : badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.s

# target to generate assembly for a file
badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.s
.PHONY : badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.cpp.s

badger/src/Badger/Platform/Windows/WindowsWindow.o: badger/src/Badger/Platform/Windows/WindowsWindow.cpp.o

.PHONY : badger/src/Badger/Platform/Windows/WindowsWindow.o

# target to build an object file
badger/src/Badger/Platform/Windows/WindowsWindow.cpp.o:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Platform/Windows/WindowsWindow.cpp.o
.PHONY : badger/src/Badger/Platform/Windows/WindowsWindow.cpp.o

badger/src/Badger/Platform/Windows/WindowsWindow.i: badger/src/Badger/Platform/Windows/WindowsWindow.cpp.i

.PHONY : badger/src/Badger/Platform/Windows/WindowsWindow.i

# target to preprocess a source file
badger/src/Badger/Platform/Windows/WindowsWindow.cpp.i:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Platform/Windows/WindowsWindow.cpp.i
.PHONY : badger/src/Badger/Platform/Windows/WindowsWindow.cpp.i

badger/src/Badger/Platform/Windows/WindowsWindow.s: badger/src/Badger/Platform/Windows/WindowsWindow.cpp.s

.PHONY : badger/src/Badger/Platform/Windows/WindowsWindow.s

# target to generate assembly for a file
badger/src/Badger/Platform/Windows/WindowsWindow.cpp.s:
	$(MAKE) -f CMakeFiles/badger.dir/build.make CMakeFiles/badger.dir/badger/src/Badger/Platform/Windows/WindowsWindow.cpp.s
.PHONY : badger/src/Badger/Platform/Windows/WindowsWindow.cpp.s

game/src/SandboxApp.o: game/src/SandboxApp.cpp.o

.PHONY : game/src/SandboxApp.o

# target to build an object file
game/src/SandboxApp.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/src/SandboxApp.cpp.o
.PHONY : game/src/SandboxApp.cpp.o

game/src/SandboxApp.i: game/src/SandboxApp.cpp.i

.PHONY : game/src/SandboxApp.i

# target to preprocess a source file
game/src/SandboxApp.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/src/SandboxApp.cpp.i
.PHONY : game/src/SandboxApp.cpp.i

game/src/SandboxApp.s: game/src/SandboxApp.cpp.s

.PHONY : game/src/SandboxApp.s

# target to generate assembly for a file
game/src/SandboxApp.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/src/SandboxApp.cpp.s
.PHONY : game/src/SandboxApp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... game"
	@echo "... badger"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... glad"
	@echo "... imgui"
	@echo "... badger/src/Badger/Application.o"
	@echo "... badger/src/Badger/Application.i"
	@echo "... badger/src/Badger/Application.s"
	@echo "... badger/src/Badger/ImGui/ImGuiLayer.o"
	@echo "... badger/src/Badger/ImGui/ImGuiLayer.i"
	@echo "... badger/src/Badger/ImGui/ImGuiLayer.s"
	@echo "... badger/src/Badger/Layer.o"
	@echo "... badger/src/Badger/Layer.i"
	@echo "... badger/src/Badger/Layer.s"
	@echo "... badger/src/Badger/LayerStack.o"
	@echo "... badger/src/Badger/LayerStack.i"
	@echo "... badger/src/Badger/LayerStack.s"
	@echo "... badger/src/Badger/Log.o"
	@echo "... badger/src/Badger/Log.i"
	@echo "... badger/src/Badger/Log.s"
	@echo "... badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.o"
	@echo "... badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.i"
	@echo "... badger/src/Badger/Platform/OpenGL/ImGuiOpenGLRenderer.s"
	@echo "... badger/src/Badger/Platform/Windows/WindowsWindow.o"
	@echo "... badger/src/Badger/Platform/Windows/WindowsWindow.i"
	@echo "... badger/src/Badger/Platform/Windows/WindowsWindow.s"
	@echo "... game/src/SandboxApp.o"
	@echo "... game/src/SandboxApp.i"
	@echo "... game/src/SandboxApp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

